### ISSUE TITLE
add replace method for easy use

### ISSUE THREAD

**Issue by wacdev** [daac-tools/daachorse#96]
as title

**Comment by vbkaisetsu** [comment]
To conclude first, I believe that the replace method should not be added to daachorse.

There are two main possible specifications for the replace method for multiple patterns as follows:
1. Replaces all multiple string patterns with a fixed single string
2. Replaces each pattern with a string that is individually associated with each pattern

Also, depending on the difference between bytewise and charwise, it is necessary to consider whether the function should return `String` or `Vec<u8>`.

The specification of the replace method varies greatly depending on the application. For this reason, I believe it is better to implement it outside of daachorse rather than adding it to daachorse.
